CREATE TABLE IF NOT EXISTS referrals (
    id SERIAL PRIMARY KEY,
    candidate_name VARCHAR(255) NOT NULL,
    candidate_skills TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE referrals
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'Eingegangen';